[build]
  # Command to build your site
  command = "npm run build"
  # Directory to output the build with client artifacts
  publish = "dist"

# First, let static assets pass through (not handled by SPA routing)
[[redirects]]
  from = "/preview.jpg"
  to = "/preview.jpg"
  status = 200

# Allow images pass through
[[redirects]]
  from = "/*.jpg"
  to = "/:splat.jpg"
  status = 200

[[redirects]]
  from = "/*.png"
  to = "/:splat.png"
  status = 200

[[redirects]]
  from = "/*.svg"
  to = "/:splat.svg"
  status = 200

# Also allow other static assets to pass through
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Then handle all other routes with SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment settings
[build.environment]
  # Set Node version
  NODE_VERSION = "20"
  NPM_VERSION = "10" # You can adjust this based on your needs

# Forms configuration
[forms]
  # Contact form settings
  [forms.contact]
    # You'll need to set up this email in the Netlify dashboard
    email_notifications_enabled = true
    # Use custom email notification template
    template = "email-templates/contact-notification.html"
  
  # Subscribe form settings
  [forms.subscribe]
    # Also enable email notifications for subscribe form
    email_notifications_enabled = true
    # Use custom email notification template
    template = "email-templates/subscribe-notification.html"