[build]
  # Command to build your site
  command = "npm run build"
  # Directory to output the build with client artifacts
  publish = "dist"

# Handle single page application routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment settings
[build.environment]
  # Set Node version
  NODE_VERSION = "20"
  NPM_VERSION = "10" # You can adjust this based on your needs