[build]
  # Command to build your site
  command = "npm run build"
  # Directory to output the build with client artifacts
  publish = "dist"

# First redirect rule for thank-you.html
[[redirects]]
  from = "/thank-you.html"
  to = "/thank-you.html"
  status = 200

# Second redirect rule for subscribe-thank-you.html
[[redirects]]
  from = "/subscribe-thank-you.html"
  to = "/subscribe-thank-you.html"
  status = 200

# Then handle all other routes with SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment settings
[build.environment]
  # Set Node version
  NODE_VERSION = "20"
  NPM_VERSION = "10" # You can adjust this based on your needs

# Forms configuration
[forms]
  # Contact form settings
  [forms.contact]
    # You'll need to set up this email in the Netlify dashboard
    email_notifications_enabled = true
    # Use custom email notification template
    template = "email-templates/contact-notification.html"
    # Specify success redirect
    success_url = "/thank-you.html"
  
  # Subscribe form settings
  [forms.subscribe]
    # Also enable email notifications for subscribe form
    email_notifications_enabled = true
    # Use custom email notification template
    template = "email-templates/subscribe-notification.html"
    # Specify success redirect
    success_url = "/subscribe-thank-you.html"