backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Publish mode enables editorial workflow for content approval
publish_mode: editorial_workflow

# Media folder (where media will be stored)
media_folder: "public/images/uploads"
public_folder: "/images/uploads"

# Collections define the structure for different content types
collections:
  # Blog posts collection
  - name: "blog"
    label: "Blog Posts"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "coverImage", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
  
  # Resources collection
  - name: "resources"
    label: "Resources"
    folder: "content/resources"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "coverImage", widget: "image", required: false }
      - { label: "Content", name: "body", widget: "markdown" }
      - { label: "Resource Type", name: "type", widget: "select", options: ["devotional", "worksheet", "guide", "video", "audio"] }
  
  # Pages collection for editable static pages
  - name: "pages"
    label: "Pages"
    files:
      - name: "home"
        label: "Home Page"
        file: "content/pages/home.md"
        fields:
          - { label: "Hero Title", name: "heroTitle", widget: "string" }
          - { label: "Hero Subtitle", name: "heroSubtitle", widget: "string" }
          - { label: "Hero Image", name: "heroImage", widget: "image", required: false }
          - { label: "About Section Title", name: "aboutTitle", widget: "string" }
          - { label: "About Section Content", name: "aboutContent", widget: "markdown" }
          - { label: "Featured Content", name: "featured", widget: "list", fields: [
              { label: "Title", name: "title", widget: "string" },
              { label: "Description", name: "description", widget: "text" },
              { label: "Image", name: "image", widget: "image", required: false },
              { label: "Link", name: "link", widget: "string" }
            ] }
      
      - name: "about"
        label: "About Page"
        file: "content/pages/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Main Image", name: "mainImage", widget: "image", required: false }
          - { label: "Content", name: "body", widget: "markdown" }
          - { label: "Team Members", name: "team", widget: "list", fields: [
              { label: "Name", name: "name", widget: "string" },
              { label: "Role", name: "role", widget: "string" },
              { label: "Bio", name: "bio", widget: "text" },
              { label: "Photo", name: "photo", widget: "image", required: false }
            ] }
      
      - name: "contact"
        label: "Contact Page"
        file: "content/pages/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "body", widget: "markdown" }
          - { label: "Form Introduction", name: "formIntro", widget: "text" }
          - { label: "Contact Email", name: "email", widget: "string" }